### ISSUE TITLE
MontoyaApi does not support displaying Chinese.

### ISSUE THREAD

**Issue by virtualmx** [PortSwigger/burp-extensions-montoya-api#33]
version: v2023.1.2 pro
api.logging().logToOutput("你好世界 Hello World");

<img width="245" alt="微信截图_20230212212610" src="https://user-images.githubusercontent.com/36029234/218313814-785cbf91-5233-4370-a1ac-9f44a3651f15.png">

**Comment by Hannah-PortSwigger** [comment]
Hi.
If you go to "Settings > Search > Character sets", do you have the option set to "Recognise automatically based on message headers"?

It looks like that output is on the popup that appears when you load an extension. If you look at the output in the "Extensions > Installed" tab, does it have the correct output?

**Comment by virtualmx** [comment]
"Recognise automatically based on message headers" is set;
<img width="476" alt="微信截图_20230214163510" src="https://user-images.githubusercontent.com/36029234/218683790-7d866440-a707-4262-aae6-05e0adf04f8e.png">
<img width="392" alt="微信截图_20230214163626" src="https://user-images.githubusercontent.com/36029234/218683794-d1adc1fa-0e18-4d9f-a590-ee071b79c88d.png">

**Comment by Hannah-PortSwigger** [comment]
Thanks for that screenshot! It looks like this is displaying correctly in the main Burp panel, and the popup output is displaying the data as raw bytes.

We've raised a bug report to make sure that both of these outputs are consistent. In the meantime, it would be best to use the output panel within Burp, rather than the popup panel.
