### ISSUE TITLE
messageID does not uniquely identify the request

### ISSUE THREAD

**Issue by sro0815** [PortSwigger/burp-extensions-montoya-api#38]
The exact same request receives a different messageID in the ProxyRequestHandler than in the HttpHandler.

Burp Version                     2023.3
Build Number                   19417
Product Name                   Burp Suite Professional
Update Channel                Early-Adopter

![grafik](https://user-images.githubusercontent.com/67997143/224638523-fcb0fd9a-88fa-4c8d-80d2-a7f4f81089e6.png)

**Comment by Hannah-PortSwigger** [comment]
Hi

This is intentional behavior. The ProxyHandler counter is separate from the HttpHandler counter.

In Burp, if you look at the Proxy History tab and compare it to the Logger tab, you'll see that the same request has a different number attached to it. This is because items in Logger/HttpHandler items include requests and responses from other tools, rather than just the Proxy.

Please let us know if you have any other questions.
