### ISSUE TITLE
HttpRequest&HttpResponse  withAddedHeader function throw java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by outlaws-bai** [PortSwigger/burp-extensions-montoya-api#90]
The code is as follows. My requirement is to add a response header to both the request and response headers, but I have found that using the success code block can meet my requirement. However, if using the code block at fail to execute, a Java. lang.ArrayIndexOutOfBoundsException exception will occur.

```
public class CounterHttpHandler implements HttpHandler {
    @Override
    public RequestToBeSentAction handleHttpRequestToBeSent(HttpRequestToBeSent httpRequestToBeSent) {
        if (BurpExtMain.status == Status.STOP) {
            return RequestToBeSentAction.continueWith(httpRequestToBeSent);
        }
        // success
//        HttpRequest request = httpRequestToBeSent.withAddedHeader("handleHttpRequestToBeSent", "success");

        // fail
        HttpRequest request = HttpRequest.httpRequest(httpRequestToBeSent.body());
        request = request.withAddedHeader("handleHttpRequestToBeSent", "success");

        return RequestToBeSentAction.continueWith(request);
    }

    @Override
    public ResponseReceivedAction handleHttpResponseReceived(HttpResponseReceived httpResponseReceived) {
        if (BurpExtMain.status == Status.STOP) {
            return ResponseReceivedAction.continueWith(httpResponseReceived);
        }


        // success
//        HttpResponse response = httpResponseReceived.withAddedHeader("handleHttpResponseReceived", "success");

        // fail
        HttpResponse response = HttpResponse.httpResponse(httpResponseReceived.body());
        response = response.withAddedHeader("handleHttpResponseReceived", "success");

        return ResponseReceivedAction.continueWith(response);
    }
}
```

Although the success method can meet the above requirements, the real requirement is that I need to send all headers to the remote end, modify them remotely, and then return them, so I must use the AddedHeader method to work properly.

**Comment by outlaws-bai** [comment]
```
public class CounterHttpHandler implements HttpHandler {
    @Override
    public RequestToBeSentAction handleHttpRequestToBeSent(HttpRequestToBeSent httpRequestToBeSent) {
        if (BurpExtMain.status == Status.STOP) {
            return RequestToBeSentAction.continueWith(httpRequestToBeSent);
        }
        // success
//        HttpRequest request = httpRequestToBeSent.withAddedHeader("handleHttpRequestToBeSent", "success");

        // fail
        HttpRequest request = HttpRequest.httpRequest(httpRequestToBeSent.body());
        request = request.withAddedHeader("handleHttpRequestToBeSent", "success");

        return RequestToBeSentAction.continueWith(request);
    }

    @Override
    public ResponseReceivedAction handleHttpResponseReceived(HttpResponseReceived httpResponseReceived) {
        if (BurpExtMain.status == Status.STOP) {
            return ResponseReceivedAction.continueWith(httpResponseReceived);
        }

        // success
//        HttpResponse response = httpResponseReceived.withAddedHeader("handleHttpResponseReceived", "success");

        // fail
        HttpResponse response = HttpResponse.httpResponse(httpResponseReceived.body());
        response = response.withAddedHeader("handleHttpResponseReceived", "success");

        return ResponseReceivedAction.continueWith(response);
    }
}
```

**Comment by Hannah-PortSwigger** [comment]
Hi

In `HttpRequest request = HttpRequest.httpRequest(httpRequestToBeSent.body());`, you are creating a request using the String parameter. This means that the only content you are providing to this request is the body content.

Due to this, you don't have an initial request line or any headers present. When you provide request content in the form of a String or a ByteArray, we assume that this is the exact data that you wish to send as part of the request, with no modifications.

Depending on how you are wanting to use the request, you could do something like:
`HttpRequest request = HttpRequest.httpRequest().withBody(requestToBeSent.body());` or `HttpRequest request = HttpRequest.httpRequest().withDefaultHeaders().withBody(requestToBeSent.body());`

Please bear in mind that these requests do not have a service set, so you may need to provide this as well as a `Host` header.

Could you provide some more information about the general functionality you are trying to achieve?

**Comment by outlaws-bai** [comment]
Thank you, I think I misunderstood the purpose of this construction method at the beginning

`Static HttpRequest (ByteArray request)`

I want to convert the DTO (HttpHeader, HttpRequest, HttpResponse) in Burp into my custom DTO, and then send it to the remote end (grpc, http...). After the remote modification, It will return my custom DTO. After returning, I need to convert the custom DTO back to the DTO (HttpHeader, HttpRequest, HttpResponse) in Burp. Currently, there are two methods to solve my needs

1. Use the default construction method, and then call multiple with* until I get the results I need

2. Convert my custom DTO into a request/response message, and then use 

`static HttpRequest (ByteArray request)`


I am currently implementing using method 2, but in method 1, I found that HttpRequest&HttpResponse do not have the ability to batch add headers, which I believe is a common requirement.

**Comment by Hannah-PortSwigger** [comment]
Thank you for the clarification!

We have an ongoing feature request to be able to provide a list of headers as an argument, similar to how you can do so with Parameters. I've added your +1 to this request.

In the meantime, we'd recommend that you reassemble your request into a `String` or `ByteArray` format, and use that to reconstruct your request with all the required headers.

Please note that if you wish to send this request, you will have to provide it with an `HttpService`, so that Burp is aware of the target to send the request to.

**Comment by outlaws-bai** [comment]
Okay, thank you for your reminder
