### ISSUE TITLE
Reading Data from MESSAGE_VIEWER_REQUEST and MESSAGE_VIEWER_RESPONSE

### ISSUE THREAD

**Issue by rahulr311295** [PortSwigger/burp-extensions-montoya-api#99]
I am writing a burp suite extension where i want to log edited request / edited response from the proxy history.
I have created a context menu that reads data from the proxy history using this i was able to find that the edited request and responses are located in the MESSAGE_VIEWER_REQUEST and MESSAGE_VIEWER_RESPONSE invocation type.

is there a way to read the request and response from these invocations

**Comment by Hannah-PortSwigger** [comment]
Hi

You can use a context menu item to perform actions on this data. I've provided an example below.

Please note the following:
- You will need to switch the editor view over to the edited request, then use the context menu to perform your action.
- I've not null-checked the optional as in this context there has to be a `MessageEditorRequestResponse` present due to the previous `if` statement.

If you wanted to perform this as a bulk action, you would likely need to use `montoyaApi.proxy().history()` so that you can use `ProxyHttpRequestResponse.finalRequest()` to retrieve the edited response of multiple items.


```java
import burp.api.montoya.BurpExtension;
import burp.api.montoya.MontoyaApi;
import burp.api.montoya.ui.contextmenu.ContextMenuEvent;
import burp.api.montoya.ui.contextmenu.ContextMenuItemsProvider;

import javax.swing.*;
import java.awt.*;
import java.util.List;

import static burp.api.montoya.ui.contextmenu.InvocationType.MESSAGE_VIEWER_REQUEST;
import static burp.api.montoya.ui.contextmenu.InvocationType.MESSAGE_VIEWER_RESPONSE;
import static java.util.Collections.emptyList;

@SuppressWarnings("unused")
public class Extension implements BurpExtension
{
    @Override
    public void initialize(MontoyaApi montoyaApi)
    {
        montoyaApi.userInterface().registerContextMenuItemsProvider(new ContextMenuItemsProvider()
        {
            @Override
            public List<Component> provideMenuItems(ContextMenuEvent event)
            {
                if (event.isFrom(MESSAGE_VIEWER_REQUEST, MESSAGE_VIEWER_RESPONSE))
                {
                    JMenuItem menuItem = new JMenuItem("Print");
                    menuItem.addActionListener(l -> {
                        montoyaApi.logging().logToOutput(event.messageEditorRequestResponse().get().requestResponse().request().toString());
                    });

                    return List.of(menuItem);
                }

                return emptyList();
            }
        });
    }
}
```

**Comment by rahulr311295** [comment]
Hi @Hannah-PortSwigger ,

Thank you for the clarification i was able to get the data

**Comment by Hannah-PortSwigger** [comment]
Glad to hear it!
